# Generated by Django 2.1.2 on 2018-10-20 06:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ContractorInformation')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PropertyOwnerInformation')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connections.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
