# Generated by Django 2.1.2 on 2018-10-20 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contractorinformation_services'),
        ('connections', '0003_auto_20181020_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.ContractorInformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connections.Job'),
        ),
    ]
