# Generated by Django 2.1.2 on 2018-10-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_auto_20181020_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
