# Generated by Django 2.1.2 on 2018-10-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_auto_20181020_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='property_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.PropertyOwnerInformation'),
        ),
    ]
