# Generated by Django 2.1.2 on 2018-10-20 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_auto_20181020_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='no desc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ContractorInformation'),
        ),
        migrations.AlterField(
            model_name='job',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='connections.Service'),
        ),
    ]
