# Generated by Django 2.1.2 on 2018-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181020_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyownerinformation',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='connections.Review'),
        ),
    ]
